# Generated by Django 4.2.5 on 2023-09-24 06:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время запуска рассылки')),
                ('frequency', models.CharField(choices=[('DAY', 'раз в день'), ('WEEK', 'раз в неделю'), ('MONTH', 'раз в месяц')], max_length=100, verbose_name='Периодичность')),
                ('status', models.CharField(blank=True, choices=[('FINISH', 'завершена'), ('CREATE', 'создана'), ('START', 'запущена')], max_length=100, null=True, verbose_name='Статус')),
                ('tag', models.CharField(choices=[('Potential client', 'Potential client'), ('Active client', 'Active client'), ('Former client', 'Former client')], max_length=50, verbose_name='тэг клиента')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('finish_at', models.DateTimeField(verbose_name='Дата и время завершения рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='признак активности')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('create_at',),
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('status', models.CharField(choices=[('Success', 'успешно'), ('Failure', 'отказ')], max_length=100, verbose_name='Статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'лог отправки письма',
                'verbose_name_plural': 'логи отправок писем',
            },
        ),
    ]
