# Generated by Django 4.2.5 on 2023-09-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания статистики')),
                ('tag', models.CharField(choices=[('Potential client', 'Potential client'), ('Active client', 'Active client'), ('Former client', 'Former client')], max_length=50, verbose_name='тэг рассылки')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='количество рассылок')),
            ],
            options={
                'verbose_name': 'статистика',
                'verbose_name_plural': 'статистики',
            },
        ),
    ]
